- hosts: apps
  gather_facts: false

  tasks:

  - name: Smoketest Postgres database
    postgresql_ping:
      db: flask_db
      login_host: "{{ groups.appdbs[0] }}"
      login_user: flask
      login_password: redhat
      ssl_mode: disable
    delegate_to: "{{ groups.apps[0] }}"
    run_once: true

- hosts: localhost
  gather_facts: false
  tasks:

  - name: Curl website from localhost
    uri:
      url: "http://{{ __frontend }}/ping"
      return_content: yes
    loop: '{{ groups.frontends }}'
    loop_control:
      loop_var: __frontend
    register: webpage
    until: '"alive" in webpage.content'
    retries: 10
    delay: 1