---
# tasks file for osp.inventory
- name: Fetch Instance Info
  os_server_info:
    cloud: openstack
    region_name: regionOne
  register: osp_instances

- name: Add host
  add_host:
    name: "{{ item.public_v4 }}"
    ansible_user: cloud-user
    ansible_ssh_private_key_file: "~/.ssh/test_id_rsa"
    group:
      - "{{ item.metadata.group }}"
      - "{{ item.metadata.deployment_name }}"
  loop: "{{ osp_instances.openstack_servers }}"